CREATE TABLE UM_USER (USER_ID INTEGER NOT NULL AUTO_INCREMENT, USER_NAME VARCHAR(100), PASSWORD VARCHAR(100), PRIMARY KEY(USER_ID));
INSERT INTO UM_USER (USER_NAME, PASSWORD) values ('Alice', 'qazqaz');
INSERT INTO UM_USER (USER_NAME, PASSWORD) values ('Bob', 'qazqaz');
INSERT INTO UM_USER (USER_NAME, PASSWORD) values ('Peter', 'qazqaz');

CREATE TABLE UM_USER_ATTRIBUTE (ATTRIBUTE_ID INTEGER NOT NULL AUTO_INCREMENT,ATTRIBUTE_NAME VARCHAR(100),
ATTRIBUTE_VALUE VARCHAR(100), USER_ID INTEGER, PRIMARY KEY(ATTRIBUTE_ID));
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('email', 'alice@gmail.com', 1);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('email', 'bob@gmail.com', 2);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('email', 'peter@gmail.com', 3);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('privilege', 'blue', 1);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('privilege', 'silver', 2);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('privilege', 'gold', 3);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('point', '1000', 1);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('point', '5900', 2);
INSERT INTO UM_USER_ATTRIBUTE (ATTRIBUTE_NAME, ATTRIBUTE_VALUE, USER_ID) value ('point', '14565', 3);
